### ISSUE TITLE
tclie_init(): Output function gets &tclie_t, not arg as expected.

### ISSUE THREAD

**Issue by jmcmullan** [dpse/tcli#2]
When using `tclie_init(&tclie, output_fn, output_fn_arg)`, the output function is being called with `&tclie` instead of `arg`.

Is this expected?

When using `tcli_init(&tcli, output_fn, output_fn_arg)`, the output function is called with `output_fn_arg`, as I would expect.

**Comment by dpse** [comment]
Thanks! It's a bug: `arg` should be passed as one would expect. I'll get it fixed!
